import {
  WebSocketGateway,
  SubscribeMessage,
  MessageBody,
  WebSocketServer,
  ConnectedSocket,
  OnGatewayConnection,
  OnGatewayDisconnect,
  OnGatewayInit,
} from '@nestjs/websockets';
import { Logger } from '@nestjs/common';
import { Server, Socket } from 'socket.io';
import { JwtService } from '@nestjs/jwt';
import { StreamingService } from './streaming.service';
import {
  AuthenticatedSocket,
  authenticateSocket,
} from '../../common/middleware/ws-jwt-auth.middleware';
import { OnEvent } from '@nestjs/event-emitter';

interface ViewerJoinPayload {
  streamKey: string;
}

interface ViewerLeavePayload {
  streamKey: string;
}

// Stream keys are 32-char hex strings generated by randomBytes(16).toString('hex')
const STREAM_KEY_REGEX = /^[a-f0-9]{32}$/;

@WebSocketGateway({
  namespace: 'streaming',
  cors: {
    origin: process.env.CORS_ORIGINS?.split(','),
    credentials: true,
  },
})
export class StreamingGateway implements OnGatewayConnection, OnGatewayDisconnect, OnGatewayInit {
  @WebSocketServer()
  server: Server;

  private readonly logger = new Logger(StreamingGateway.name);

  // Track which streams each socket is watching
  private readonly socketStreams = new Map<string, string>();

  constructor(
    private readonly jwtService: JwtService,
    private readonly streamingService: StreamingService,
  ) {}

  afterInit(_server: Server) {
    this.logger.log('Streaming Gateway initialized');
  }

  async handleConnection(client: Socket) {
    try {
      const authenticatedClient = await authenticateSocket(client, this.jwtService);

      this.logger.log(
        `Client connected: ${authenticatedClient.id} (User: ${authenticatedClient.user.userId})`,
      );

      client.emit('connection:success', {
        type: 'connection:success',
        data: {
          message: 'Connected to streaming server',
          userId: authenticatedClient.user.userId,
          timestamp: new Date().toISOString(),
        },
      });
    } catch (error) {
      this.logger.error(`Connection failed: ${error.message}`);
      client.emit('error', {
        type: 'error',
        errorCode: 'AUTH_FAILED',
        message: 'Authentication failed',
        timestamp: new Date().toISOString(),
      });
      client.disconnect();
    }
  }

  async handleDisconnect(client: Socket) {
    this.logger.log(`Client disconnected: ${client.id}`);

    const streamKey = this.socketStreams.get(client.id);
    if (streamKey) {
      await this.handleViewerLeave(client, streamKey);
    }
  }

  @SubscribeMessage('stream:viewer:join')
  async handleViewerJoin(
    @ConnectedSocket() client: AuthenticatedSocket,
    @MessageBody() payload: ViewerJoinPayload,
  ) {
    const { streamKey } = payload;

    // Validate stream key format
    if (!streamKey || !STREAM_KEY_REGEX.test(streamKey)) {
      client.emit('error', {
        type: 'error',
        errorCode: 'INVALID_STREAM_KEY',
        message: 'Invalid stream key format',
        timestamp: new Date().toISOString(),
      });
      return;
    }

    // Verify stream is actually live
    const status = await this.streamingService.getStreamStatusByKey(streamKey);
    if (status.status !== 'LIVE') {
      client.emit('error', {
        type: 'error',
        errorCode: 'STREAM_NOT_LIVE',
        message: 'Stream is not currently live',
        timestamp: new Date().toISOString(),
      });
      return;
    }

    const roomName = `stream:${streamKey}`;

    await client.join(roomName);
    this.socketStreams.set(client.id, streamKey);

    const viewerCount = await this.streamingService.updateViewerCount(streamKey, 1);

    this.logger.log(
      `User ${client.user.userId} joined stream ${streamKey} (viewers: ${viewerCount})`,
    );

    this.server.to(roomName).emit('stream:viewer-count', {
      type: 'stream:viewer-count',
      data: {
        streamKey,
        viewerCount,
        timestamp: new Date().toISOString(),
      },
    });

    return {
      type: 'stream:viewer:join:success',
      data: {
        streamKey,
        viewerCount,
        timestamp: new Date().toISOString(),
      },
    };
  }

  @SubscribeMessage('stream:viewer:leave')
  async handleViewerLeaveMessage(
    @ConnectedSocket() client: AuthenticatedSocket,
    @MessageBody() payload: ViewerLeavePayload,
  ) {
    const { streamKey } = payload;
    await this.handleViewerLeave(client, streamKey);

    return {
      type: 'stream:viewer:leave:success',
      data: {
        streamKey,
        timestamp: new Date().toISOString(),
      },
    };
  }

  private async handleViewerLeave(client: Socket, streamKey: string) {
    const roomName = `stream:${streamKey}`;

    await client.leave(roomName);
    this.socketStreams.delete(client.id);

    const viewerCount = await this.streamingService.updateViewerCount(streamKey, -1);

    this.logger.log(`Client ${client.id} left stream ${streamKey} (viewers: ${viewerCount})`);

    this.server.to(roomName).emit('stream:viewer-count', {
      type: 'stream:viewer-count',
      data: {
        streamKey,
        viewerCount,
        timestamp: new Date().toISOString(),
      },
    });
  }

  @OnEvent('stream:ended')
  handleStreamEnded(payload: { streamId: string; streamKey: string }) {
    if (!payload.streamKey) {
      return;
    }
    const roomName = `stream:${payload.streamKey}`;
    this.logger.log(`Broadcasting stream:ended to room ${roomName}`);
    this.server.to(roomName).emit('stream:ended', {
      streamKey: payload.streamKey,
    });
  }
}
